/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EstoqueController;
import dao.ControleEstoqueDao;
import dao.ProdutoDao;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.ControleEstoque;
import model.Produto;
import org.apache.commons.lang3.StringUtils;
import util.Configura;
import util.Mensagem;

/**
 *
 * @author vagner
 */
public class JPanelControleEstoque extends javax.swing.JPanel {

    /**
     * Creates new form JPanelControleEstooque
     */
    
    private ProdutoDao produtoDao;
    private List<Produto> produtos;
    private EstoqueController controller;
    private ControleEstoqueDao dao;
    private List<ControleEstoque> lista;
    
    public JPanelControleEstoque() {
        initComponents();
        this.produtoDao = new ProdutoDao();
        this.produtos = new ArrayList<>();
        this.controller = new EstoqueController();
        this.dao = new ControleEstoqueDao();
        this.lista = new ArrayList<ControleEstoque>();
        this.atualizarProduto();
        this.atualizarTabela();
        this.limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxProdutoEstoque = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQuantidadeEstoque = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jButtonAtualizarProdutos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstoque = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(600, 194));

        jLabel1.setText("Produto:");

        jLabel2.setText("Quantidade:");

        jButtonSalvar.setText("Adicionar Qtd.");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonAtualizarProdutos.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jButtonAtualizarProdutos.setText("Atualizar");
        jButtonAtualizarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarProdutosActionPerformed(evt);
            }
        });

        jTableEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Título 3"
            }
        ));
        jTableEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEstoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEstoque);
        if (jTableEstoque.getColumnModel().getColumnCount() > 0) {
            jTableEstoque.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAtualizarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizarProdutos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarProdutosActionPerformed
        this.atualizarProduto();
    }//GEN-LAST:event_jButtonAtualizarProdutosActionPerformed

    public void limparCampos(){
        this.jComboBoxProdutoEstoque.setSelectedIndex(-1);
        this.jTextFieldQuantidadeEstoque.setText("");
        this.repaint();
    }
    private boolean validaDados() {
        
        if(this.jComboBoxProdutoEstoque.getSelectedIndex() < 0){
            Mensagem.mostrar(this, "É necessario selecionar um produto");
            return false;
        }
        if(this.jTextFieldQuantidadeEstoque.getText().trim().isEmpty()){
            Mensagem.mostrar(this, "A quantidade não pode ser vazia.");
            this.jTextFieldQuantidadeEstoque.requestFocus();
            return false;
        }
        if(!StringUtils.isNumeric(this.jTextFieldQuantidadeEstoque.getText())){
            Mensagem.mostrar(this, "A quantidade é um numero inteiro.");
            this.jTextFieldQuantidadeEstoque.requestFocus();
            return false;
        }
        
        return true;
    }


    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
        if(this.validaDados()){
            this.controller.entidade.setProduto(produtos.get(this.jComboBoxProdutoEstoque.getSelectedIndex()));
            this.controller.entidade.setQuantidade(Double.parseDouble(this.jTextFieldQuantidadeEstoque.getText()));

            this.controller.gravar();

            this.controller.limpar();
            this.limparCampos();
            this.atualizarTabela();
        }
             
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jTableEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstoqueMouseClicked
        this.controller.getObjectToJtable(evt);
        
        int index = 0;
        for (Produto produto : produtos) {
            if(this.controller.entidade.getProduto().getId().equals(produto.getId())){
                this.jComboBoxProdutoEstoque.setSelectedIndex(index);
                break;
            }
            index++;
        }        
        this.jTextFieldQuantidadeEstoque.setText(this.controller.entidade.getQuantidade().toString());
        
    }//GEN-LAST:event_jTableEstoqueMouseClicked

    private void atualizarProduto(){
        try {
            this.produtos.clear();
            this.produtos = this.produtoDao.buscarLista(new Produto());
            this.jComboBoxProdutoEstoque.removeAllItems();
            this.jComboBoxProdutoEstoque.setSelectedIndex(-1);
            produtos.forEach((produto) -> {
                this.jComboBoxProdutoEstoque.addItem(produto.toString());
            });
            this.limparCampos();
            this.repaint();
        } catch (Exception ex) {
            Logger.getLogger(JPanelControleEstoque.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarProdutos;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxProdutoEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstoque;
    private javax.swing.JTextField jTextFieldQuantidadeEstoque;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela() {        
        try {           
            this.controller.buscarLista();
            Configura.tabela(this.jTableEstoque, this.controller.lista);
            this.repaint();
        } catch (Exception ex) {
            Logger.getLogger(JPanelControleEstoque.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
