/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProdutoController;
import java.awt.Window;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import org.apache.commons.lang3.StringUtils;
import util.Configura;
import util.Mensagem;

/**
 *
 * @author vagner
 */
public class JPanelProduto extends javax.swing.JPanel {

    
    private ProdutoController controller;
    
    /**
     * Creates new form JPanelProduto
     */
    public JPanelProduto() {
        initComponents();
        
        this.controller = new ProdutoController();
        this.limparCampos();
        this.atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTipoEmbalagem = new javax.swing.JTextField();
        jTextFieldQuantidadeEmbalagem = new javax.swing.JTextField();
        jTextFieldValorProduto = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();

        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(600, 194));
        setLayout(null);

        jLabel1.setText("Nome:");
        add(jLabel1);
        jLabel1.setBounds(6, 6, 45, 15);
        add(jTextFieldNomeProduto);
        jTextFieldNomeProduto.setBounds(6, 27, 587, 23);

        jLabel2.setText("Tipo de Embalagem:");
        add(jLabel2);
        jLabel2.setBounds(6, 56, 142, 15);

        jLabel3.setText("Quantidade Embalagem:");
        add(jLabel3);
        jLabel3.setBounds(267, 56, 173, 15);

        jLabel4.setText("Valor:");
        add(jLabel4);
        jLabel4.setBounds(452, 56, 80, 15);
        add(jTextFieldTipoEmbalagem);
        jTextFieldTipoEmbalagem.setBounds(6, 77, 249, 23);
        add(jTextFieldQuantidadeEmbalagem);
        jTextFieldQuantidadeEmbalagem.setBounds(267, 77, 161, 23);
        add(jTextFieldValorProduto);
        jTextFieldValorProduto.setBounds(452, 77, 141, 23);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        add(jButtonSalvar);
        jButtonSalvar.setBounds(332, 106, 114, 31);

        jButtonFechar.setLabel("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        add(jButtonFechar);
        jButtonFechar.setBounds(452, 106, 141, 31);

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableProdutos);

        add(jScrollPane2);
        jScrollPane2.setBounds(6, 143, 587, 168);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        try {
            Window w = SwingUtilities.getWindowAncestor(JPanelProduto.this);
            w.setVisible(false);
        } catch (Throwable ex) {
            Logger.getLogger(JPanelProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private boolean validaDados(){
        if(!StringUtils.isNumeric(this.jTextFieldQuantidadeEmbalagem.getText())){
            Mensagem.mostrar(this, "Quantidade de Embalagem é um numero inteiro");
            this.jTextFieldQuantidadeEmbalagem.requestFocus();
            return false;
        }
        if(!StringUtils.isNumeric(this.jTextFieldValorProduto.getText())){
            Mensagem.mostrar(this, "O valor do produto não pode conter letras");
            this.jTextFieldValorProduto.requestFocus();
            return false;
        }        
        return true;
    }
    
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
        if(this.validaDados()){
            this.controller.entidade.setAtivo(true);
            this.controller.entidade.setNome(this.jTextFieldNomeProduto.getText());
            this.controller.entidade.setTipoEmbalagem(this.jTextFieldTipoEmbalagem.getText());
            this.controller.entidade.setQuantidadeEmbalagem(Double.parseDouble(this.jTextFieldQuantidadeEmbalagem.getText()));
            this.controller.entidade.setValor(Double.parseDouble(this.jTextFieldValorProduto.getText()));

            this.controller.gravar();
            this.limparCampos();
            this.atualizarTabela();
        }            
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    public void limparCampos(){
        this.jTextFieldNomeProduto.setText("");
        this.jTextFieldTipoEmbalagem.setText("");
        this.jTextFieldQuantidadeEmbalagem.setText("");
        this.jTextFieldValorProduto.setText("");
    }
    
    private void atualizarTabela() {
        this.controller.buscarLista();
        Configura.tabela(this.jTableProdutos, this.controller.lista);
        this.jTableProdutos.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldQuantidadeEmbalagem;
    private javax.swing.JTextField jTextFieldTipoEmbalagem;
    private javax.swing.JTextField jTextFieldValorProduto;
    // End of variables declaration//GEN-END:variables
}
